Improve colors of horizontal scrollbar
hifis-net/RSD-as-a-service pull request #45
Opened 2022-08-30 07:45 UTC by ruester

# Fix colors of horizontal scrollbar

Fixes #40

Changes proposed in this pull request:

* change the color of the scrollbar for Firefox
* change the hover color of the scroll buttons

Now the participating organisations scroll component looks the same in Firefox and Chrome:

![image](https://user-images.githubusercontent.com/1287885/187379520-72300b07-7f02-4e40-8a70-6e970223159f.png)

How to test:

* build this branch and use the scroll component on the front page

2022-08-30 09:34 UTC, cmeessen requested changes
So, the good thing is: it works on MacOS Safari.

The bad thing: it doesn't work on iOS Safari.

And then, there are some points regarding Firefox:

* the scroll bar is hidden by default
* the scroll bar is too thin
* the scroll bar jumps around when hovering
* the scroll bar edges are rounded and not at right angle
* there is a white space between the scrollbar and the lower border of the div

Sorry :/ Do you think you can find a way to fix this?

2022-09-02 10:59 UTC, ruester commented
I finally got it working by using the library [simplebar-react](https://www.npmjs.com/package/simplebar-react). I've tested this new solution also on my mobile with chrome and firefox and it works. @cmeessen please test it again for iOS/Safari

2022-09-02 11:04 UTC, ruester commented
Chrome:
![image](https://user-images.githubusercontent.com/1287885/188125752-6b245325-fc85-4b3a-91f4-3326850299c0.png)

Firefox:
![image](https://user-images.githubusercontent.com/1287885/188125817-46d2e0fb-58a8-481b-9998-dafc72b1dc1c.png)

The scrollbar from the Helmholtz homepage has `border-radius: 10px` which I also used for our scrollbar now. So it has *not* to be right angle.

From helmholtz.de:
![image](https://user-images.githubusercontent.com/1287885/188126263-0f29a7fe-33c2-4065-b73a-cbda3750e503.png)

2022-09-20 07:44 UTC, cmeessen requested changes
Good job, we are almost there. It works on iOS Safari as well as on Firefox :+1:

There are a few more things to be done (see comments). Also, the width of the scrollbar is rather small on mobile:

![image](https://user-images.githubusercontent.com/14222414/191197792-a5446e2d-2b37-4282-831d-4c01f03a5a05.png)

Having it about 1/3 of the container width would be perfect.

2022-09-20 07:44 UTC, cmeessen commented on frontend/pages/index.tsx
> +        style={{maxHeight: 300}}
`#hgf-scroll-container` is already set to 200px. Should we set this here too?

2022-09-20 07:44 UTC, cmeessen commented on frontend/styles/custom.css
>    border-bottom: 1px solid #002864;
The bottom border was missing and I added it again. However, there is a 2 pixel offset at both ends. Is there any way to fix this?

![image](https://user-images.githubusercontent.com/14222414/191195564-16562953-9bf0-4412-8712-73914129b144.png)

2022-09-20 07:44 UTC, cmeessen commented on frontend/styles/custom.css
> +  border-radius: 0px !important;
> The scrollbar from the Helmholtz homepage has border-radius: 10px which I also used for our scrollbar now. So it has not to be right angle.

The official Helmholtz brand style guide proposes a right angle scroll bar, so I changed it back.

2022-09-29 16:04 UTC, merged